// Characterization test for the site guide. Run: node --test src/lib/guide/guide.test.ts
//
// OWNER ORDER: the guide's intelligence is frozen. This file REPLACES the tests that pinned the removed
// word-boundary matcher (src/lib/guide/match.test.ts, the old guide.test.ts and golden.json). Those pinned a
// redesign-era behavior the owner did not approve; this one pins the ORIGINAL behavior (git tag
// pre-redesign-2026-09-30, src/components/DaenaGuide.tsx findBestMatch + knowledge array).
//
// The expectations below were GENERATED by running the tag's original findBestMatch over each query. Nothing
// here was written from the new code. Changing the expected index of a case means changing the frozen behavior.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { existsSync, statSync } from 'node:fs'
import { FALLBACK, GREETING, KNOWLEDGE, findBestMatch } from './legacy.ts'

const root = new URL('../../../', import.meta.url)
const sha = (t: string) => createHash('sha256').update(t).digest('hex').slice(0, 16)

/** [query, index of the original knowledge entry it must resolve to, or -1 for no match (FALLBACK)]. */
const CASES: [string, number][] = [
  ["hi",45],
  ["hello there",45],
  ["Hi!",45],
  ["HELLO",45],
  ["hey daena",10],
  ["good morning",45],
  ["what do you do",0],
  ["What does MAS-AI build?",8],
  ["who founded this company",8],
  ["who is the founder",9],
  ["are you a real person",45],
  ["are you an ai",45],
  ["who are you",8],
  ["tell me about Klyntar",8],
  ["tell me about daena",8],
  ["book a call",24],
  ["I want to book a call",24],
  ["schedule a meeting",24],
  ["how much does it cost",30],
  ["how many tests do you have",20],
  ["is it open source",39],
  ["do you have a github",39],
  ["Are you hiring?",38],
  ["I am looking for a job",43],
  ["where are you located",29],
  ["pricing",30],
  ["what is daena",10],
  ["explain how it works",32],
  ["tell me more",32],
  ["how does daena work",26],
  ["is this secure",33],
  ["do you comply with GDPR",42],
  ["EU AI Act",7],
  ["what is the ai act deadline",7],
  ["patent",12],
  ["do you have patents",12],
  ["phi lattice",45],
  ["NBMF memory",12],
  ["can you scan my website",2],
  ["pen test my app",2],
  ["vulnerability scan",2],
  ["not sure where to start",4],
  ["help me decide",4],
  ["what can you do",0],
  ["thanks",46],
  ["thank you so much",46],
  ["bye",47],
  ["see you later",47],
  ["tell me a joke",49],
  ["investors",25],
  ["we want to partner",41],
  ["healthcare ai",15],
  ["construction permits",16],
  ["contentops",14],
  ["google startup program",19],
  ["azure credits",19],
  ["competitors",36],
  ["why mas-ai",37],
  ["what makes you different",31],
  ["how many employees",28],
  ["are you a solo founder",9],
  ["contact",24],
  ["email",24],
  ["asdfghjkl",-1],
  ["qwerty",-1],
  ["",-1],
  ["   ",-1],
  ["\n\t",-1],
  ["?",-1],
  ["!!!",-1],
  ["DAENA",10],
  ["dAeNa",10],
  ["klynter",5],
  ["pricng",-1],
  ["secuirty",-1],
  ["whats ur name",-1],
  ["xyz 123",-1],
  ["what is the weather",-1],
  ["hello, what do you do?",0],
  ["this is a long sentence with hi inside words like this and that",45],
  ["  Klyntar  ",5],
  ["KLYNTAR!!!",5],
  ["mythos",6],
  ["beyond mythos",23],
  ["beyondmythos",23],
  ["anthropic security",6],
  ["frontier",6],
  ["the 10-stage pipeline",26],
  ["what is the pipeline",26],
  ["show me your work",13],
  ["what have you built",13],
  ["i need an agent",1],
  ["custom agent for my business",1],
  ["audit my website",2],
  ["security audit",2],
  ["hack my site",2],
  ["why mas-ai suggest need an agent building",1],
  ["about mas safe why daena are you real",27],
  ["why daena collaborate build for me",1],
  ["collaborate what do you agents",13],
  ["thanks investor services false positive",21],
  ["why choose how much goodbye what have you",13],
  ["take care bye tell me more",32],
  ["company impressive how many tests offensive security",5],
  ["asset shield",22],
  ["consent token",22],
  ["false positives",21],
  ["zero-fp",21],
  ["sqlmap",-1],
  ["nuclei",-1],
  ["make me laugh",49],
  ["two paths",0],
  ["paths",0],
  ["which path",0],
  ["services",0],
  ["what can you",0],
  ["offerings",0],
  ["what do you offer",0],
  ["build path",1],
  ["automation",1],
  ["install",1],
  ["installation",1],
  ["deploy ai",1],
  ["need an agent",1],
  ["build for me",1],
  ["custom agent",1],
  ["secure path",2],
  ["scan",2],
  ["vulnerability",2],
  ["audit my",2],
  ["pen test",2],
  ["hack my",2],
  ["find holes",2],
  ["exposed",2],
  ["book call",3],
  ["book consultation",3],
  ["schedule call",3],
  ["appointment",3],
  ["meeting",3],
  ["free call",3],
  ["book meeting",3],
  ["not sure",4],
  ["which one",4],
  ["dont know",4],
  ["don't know",4],
  ["recommend",4],
  ["suggest",4],
  ["klyntar",5],
  ["security platform",5],
  ["red team",5],
  ["offensive security",5],
  ["ai act",7],
  ["eu ai act",7],
  ["eu regulation",7],
  ["compliance deadline",7],
  ["what is mas-ai",8],
  ["mas-ai",8],
  ["company",8],
  ["about mas",8],
  ["tell me about",8],
  ["founder",9],
  ["masoud",9],
  ["ceo",9],
  ["who built",9],
  ["team",9],
  ["daena",10],
  ["product",10],
  ["platform",10],
  ["flagship",10],
  ["governance",11],
  ["governed",11],
  ["policy",11],
  ["audit",11],
  ["trust",11],
  ["ip",12],
  ["philattice",12],
  ["nbmf",12],
  ["architecture",12],
  ["memory",12],
  ["products",13],
  ["portfolio",13],
  ["build",13],
  ["built",13],
  ["what do you",13],
  ["what you built",13],
  ["what are you doing",13],
  ["projects",13],
  ["what have you",13],
  ["show me",13],
  ["your work",13],
  ["content",14],
  ["medsmart",15],
  ["med smart",15],
  ["healthcare",15],
  ["medical",15],
  ["construction",16],
  ["building",16],
  ["permits",16],
  ["enterprise",17],
  ["deploy",17],
  ["b2b",17],
  ["business",17],
  ["work with",17],
  ["consulting",17],
  ["industries",18],
  ["serve",18],
  ["clients",18],
  ["who use",18],
  ["sectors",18],
  ["google",19],
  ["startups",19],
  ["azure",19],
  ["gcp",19],
  ["credits",19],
  ["programs",19],
  ["test",20],
  ["demo",20],
  ["proof",20],
  ["working",20],
  ["ready",20],
  ["how many tests",20],
  ["exploit",21],
  ["signatures",21],
  ["zero fp",21],
  ["false positive",21],
  ["scanner",21],
  ["vault",22],
  ["egress",22],
  ["enrichment",23],
  ["call",24],
  ["reach",24],
  ["book",24],
  ["talk",24],
  ["meet",24],
  ["schedule",24],
  ["invest",25],
  ["funding",25],
  ["investor",25],
  ["raise",25],
  ["pitch",25],
  ["pipeline",26],
  ["stages",26],
  ["10-stage",26],
  ["technical",26],
  ["council",26],
  ["quintessence",26],
  ["who is daena",27],
  ["what are you",27],
  ["are you ai",27],
  ["are you real",27],
  ["your name",27],
  ["how many",28],
  ["size",28],
  ["employees",28],
  ["people work",28],
  ["where",29],
  ["location",29],
  ["based",29],
  ["canada",29],
  ["ontario",29],
  ["office",29],
  ["cost",30],
  ["price",30],
  ["how much",30],
  ["free",30],
  ["innovation",31],
  ["innovative",31],
  ["new",31],
  ["different",31],
  ["unique",31],
  ["special",31],
  ["how it works",32],
  ["explain",32],
  ["how does it",32],
  ["details",32],
  ["security",33],
  ["safe",33],
  ["secure",33],
  ["protect",33],
  ["risk",33],
  ["agent",34],
  ["agents",34],
  ["multi-agent",34],
  ["autonomous",34],
  ["orchestrat",34],
  ["securitygate",35],
  ["auditlog",35],
  ["competitor",36],
  ["competition",36],
  ["compare",36],
  ["vs",36],
  ["alternative",36],
  ["similar",36],
  ["other",36],
  ["why",37],
  ["why daena",37],
  ["why choose",37],
  ["advantage",37],
  ["benefit",37],
  ["hiring",38],
  ["job",38],
  ["career",38],
  ["work for",38],
  ["join",38],
  ["open position",38],
  ["role",38],
  ["open source",39],
  ["github",39],
  ["code",39],
  ["repo",39],
  ["repository",39],
  ["source code",39],
  ["when",40],
  ["launch",40],
  ["release",40],
  ["timeline",40],
  ["available",40],
  ["waitlist",40],
  ["early access",40],
  ["partner",41],
  ["partnership",41],
  ["collaborate",41],
  ["integration",41],
  ["integrate",41],
  ["compliance",42],
  ["regulation",42],
  ["regulatory",42],
  ["gdpr",42],
  ["hipaa",42],
  ["sox",42],
  ["legal",42],
  ["try",43],
  ["see",43],
  ["video",43],
  ["watch",43],
  ["preview",43],
  ["look",43],
  ["guard",44],
  ["daena guard",44],
  ["security layer",44],
  ["protection",44],
  ["hello",45],
  ["hey",45],
  ["greet",45],
  ["sup",45],
  ["yo",45],
  ["what up",45],
  ["good evening",45],
  ["thank",46],
  ["awesome",46],
  ["cool",46],
  ["great",46],
  ["nice",46],
  ["good job",46],
  ["impressive",46],
  ["goodbye",47],
  ["see you",47],
  ["later",47],
  ["take care",47],
  ["help",48],
  ["options",48],
  ["menu",48],
  ["guide",48],
  ["funny",49],
  ["joke",49],
  ["laugh",49],
  ["humor",49],
  ["two paths installation",1],
  ["two paths security audit",0],
  ["two paths book consultation",3],
  ["two paths security platform",5],
  ["two paths anthropic security",6],
  ["two paths eu ai act",7],
  ["two paths what is mas-ai",8],
  ["two paths what is daena",10],
  ["two paths what you built",13],
  ["two paths contentops",14],
  ["two paths how many tests",20],
  ["two paths how does daena work",26],
  ["two paths multi-agent",34],
  ["two paths source code",39],
  ["two paths partnership",41],
  ["two paths daena guard",44],
  ["paths secure path",2],
  ["paths not sure",4],
  ["paths founder",9],
  ["paths governance",11],
  ["paths patent",12],
  ["paths medsmart",15],
  ["paths construction",16],
  ["paths enterprise",17],
  ["paths industries",18],
  ["paths google",19],
  ["paths exploit",21],
  ["paths asset shield",22],
  ["paths beyondmythos",23],
  ["paths contact",24],
]

/** Fingerprint of every entry's keyword list in the original, in order. */
const ORIGINAL_KEYWORDS_SHA = "d2abc7a8a0a2364b"
/** Fingerprint of every original answer; a changed answer must be listed in FORCED_ANSWERS. */
const ORIGINAL_ANSWER_SHA = ["0972b73089d768f7","10c49f445d3e81a7","9af8d920a2f08a7b","655212e27af2b9ae","ccac79a7d77ed6fb","ec25d81dc47fd523","2d3bc906d1d22c6a","972be076cc3a54eb","1b8775f4d01091e4","435b2a008b9eec99","0fe1bcb4c989eab9","c89e485f5103bdf1","fdb6d5c640a1d7c8","2ad49b169429be7a","d94b93b0f06dd483","dd4c09b001b4696b","55854ea5f63f6151","4ba571a5b1addd34","6163edb3684b03e3","3c354e48777ab967","e64968b7933bc63b","c6cc8169945e86c1","ddda692bbb5f9bbd","21aa4254e636f017","e932e9f5c7f279c3","c310ec7eea638f71","ac3306d76d7effff","bd77d0b66fdb5b38","95a1679f23669b5f","e1b81e042952a629","89774645794118bc","3fbec9c16b82b342","a919fb90b71d66c5","c83c2a2fcfdc838f","4bb926c6f267caf5","8c4b5f5f839396dc","8c5a8770d433e706","3a94f1256674f38a","90718a2755b41c68","b98f24bd3dbe62f4","2c101b191e09a80f","8e81e2a062f755e8","8b25176b4603ddac","b03bea8a49e4f100","d684e2badc092299","6e71a6f09ee65093","3996292fe7679874","3d1d2357da5981d3","c43a82f3c57b4191","3123febeff191823"]
const ORIGINAL_SECTIONS: (string | null)[] = ["paths","paths","paths",null,null,"products","products",null,"hero","credibility","products","products","credibility","portfolio","portfolio","portfolio","portfolio","enterprise","enterprise","credibility","proof","products","products","products","contact","contact",null,"products","credibility","credibility","contact","credibility","products","products","products",null,"enterprise","products","contact","portfolio","contact","contact","enterprise","products","portfolio",null,null,null,null,null]
const ORIGINAL_LINKS: (string | null)[] = [null,"/automation","/security","/book","/book","/security",null,"/ai-act-readiness",null,null,"https://daena.mas-ai.co",null,null,null,null,null,null,null,null,null,null,"/security",null,null,null,null,"https://daena.mas-ai.co",null,null,null,null,null,"https://daena.mas-ai.co",null,null,"https://daena.mas-ai.co",null,null,null,"https://github.com/Mas-AI-Official",null,null,null,"https://daena.mas-ai.co",null,null,null,null,null,null]

/** Homepage section ids on the rebuilt site (src/app/page.tsx). Original ids that vanished map to live ones. */
const LIVE_SECTIONS = new Set(['hero', 'problem', 'approach', 'services', 'websites', 'deploy', 'work', 'daena', 'company', 'start', 'faq'])
const SECTION_MAP: Record<string, string> = {
  paths: 'services', products: 'daena', portfolio: 'work', enterprise: 'services',
  credibility: 'company', contact: 'start', proof: 'daena',
}
const LINK_MAP: Record<string, string> = { '/book': '/start/' }

/** Redesign-forced and owner-approved marketing answer edits (2026-09-30): index -> first 40 characters. */
const FORCED_ANSWERS: Record<number, string> = {
  "0": "We are an AI implementation and software",
  "1": "We build agents, assistants, automations",
  "5": "Klyntar is my security platform. 25+ exp",
  "6": "My scan depth is comparable to frontier-",
  "7": "I run a fixed 2-week readiness sprint: c",
  "8": "MAS-AI Technologies Inc. is a Canadian c",
  "9": "MAS-AI was founded by Masoud Masoori, a ",
  "12": "We have one US provisional patent applic",
  "13": "We build what a business is missing: aut",
  "15": "Med Smart is our AI-powered patient care",
  "17": "We cover the whole path: workflow discov",
  "18": "We build for operations-heavy businesses",
  "20": "Daena (beta) ships with an automated tes",
  "23": "Klyntar's enrichment stage runs every fi",
  "30": "Every engagement starts with the problem",
  "31": "Our key innovations are two architecture",
  "37": "Three reasons: (1) We decide before we b",
  "40": "Daena is in beta with a working demo. We",
  "41": "We connect the systems you already use, ",
  "48": "I can tell you about what we build, wher"
}

test('the knowledge base keeps the original 50 entries in the original order', () => {
  assert.equal(KNOWLEDGE.length, 50)
})

test('keywords are byte-identical to the original (matching is frozen)', () => {
  assert.equal(sha(JSON.stringify(KNOWLEDGE.map((e) => e.keywords))), ORIGINAL_KEYWORDS_SHA)
})

test('every answer is the original answer except the listed redesign-forced edits', () => {
  const changed = KNOWLEDGE.map((e, i) => (sha(e.answer) === ORIGINAL_ANSWER_SHA[i] ? -1 : i)).filter((i) => i >= 0)
  assert.deepEqual(changed, Object.keys(FORCED_ANSWERS).map(Number))
  for (const [i, first40] of Object.entries(FORCED_ANSWERS)) {
    assert.equal(KNOWLEDGE[Number(i)].answer.slice(0, 40), first40, 'entry ' + i)
  }
})

test('sections and links are the original ones except dead-target remaps', () => {
  KNOWLEDGE.forEach((e, i) => {
    const s = ORIGINAL_SECTIONS[i]
    assert.equal(e.section, s === null ? null : (SECTION_MAP[s] ?? s), 'section of entry ' + i)
    const l = ORIGINAL_LINKS[i]
    assert.equal(e.link ?? null, l === null ? null : (LINK_MAP[l] ?? l), 'link of entry ' + i)
  })
})

test('the fallback is the original fallback, verbatim', () => {
  assert.equal(
    FALLBACK,
    "I'm not sure about that one. For detailed questions, you can email masoud.masoori@mas-ai.co. Or try asking about our products, services, or team!",
  )
})

test('characterization: ' + CASES.length + ' queries resolve to the original entry', () => {
  assert.ok(CASES.length >= 60)
  const failures: string[] = []
  for (const [query, index] of CASES) {
    const match = findBestMatch(query)
    const got = match ? KNOWLEDGE.indexOf(match) : -1
    if (got !== index) failures.push(JSON.stringify(query) + ' expected ' + index + ' got ' + got)
  }
  assert.deepEqual(failures, [])
})

test('empty and whitespace input never match', () => {
  for (const q of ['', ' ', '   ', '\n\t ']) assert.equal(findBestMatch(q), null)
})

test('matching is the original substring scoring: short keywords match inside longer words', () => {
  // "this" contains "hi", so the greeting entry answers. This is the original behavior, kept on purpose.
  const m = findBestMatch('this')
  assert.ok(m)
  assert.match(m.answer, /^Hello! Welcome to MAS-AI/)
})

test('ties go to the first entry (strictly-greater scoring)', () => {
  // "services" is a keyword of entry 0 and of entry 17 with the same length, so the earlier entry wins.
  const m = findBestMatch('services')
  assert.ok(m)
  assert.equal(KNOWLEDGE.indexOf(m), 0)
})

test('every link is http(s), mailto:, a route under src/app, or a file in public/', () => {
  const routeOrFile = (link: string): boolean => {
    const path = link.split('#')[0].split('?')[0].replace(/^\/+|\/+$/g, '')
    if (path === '') return true // the homepage
    const asRoute = new URL('src/app/' + path, root)
    const asFile = new URL('public/' + path, root)
    return (existsSync(asRoute) && statSync(asRoute).isDirectory()) || (existsSync(asFile) && statSync(asFile).isFile())
  }
  const links = KNOWLEDGE.map((e) => e.link).filter((l): l is string => Boolean(l))
  assert.ok(links.length > 0)
  for (const link of links) {
    if (/^https?:\/\//.test(link) || link.startsWith('mailto:')) continue
    assert.ok(link.startsWith('/'), 'unsupported link form: ' + link)
    assert.ok(routeOrFile(link), 'dead link target: ' + link)
  }
})

test('every section is null or a live homepage id', () => {
  for (const e of KNOWLEDGE) assert.ok(e.section === null || LIVE_SECTIONS.has(e.section), 'dead section ' + e.section)
})

test('no em dash or en dash in any visible text', () => {
  const EM = String.fromCharCode(0x2014)
  const EN = String.fromCharCode(0x2013)
  for (const t of [GREETING, FALLBACK, ...KNOWLEDGE.map((e) => e.answer)]) {
    assert.ok(!t.includes(EM) && !t.includes(EN), 'dash in: ' + t.slice(0, 50))
  }
})

test('the opening greeting keeps its original wording apart from the forced edits', () => {
  assert.ok(GREETING.startsWith("Hi. I'm Daena, the governance side of MAS-AI. My security mode is called Klyntar"))
  assert.match(GREETING, /Two paths here: \(1\) we build governed AI agents/)
  assert.match(GREETING, /\u201Cnot sure\u201D and I'll help you pick\.$/)
})

// Exact full-text pins (pass 6), so a forced answer or the greeting cannot drift past its 40-character prefix.
// Changing one is an owner-approved edit: update the hash in the same change and record it in the process record.
const FORCED_ANSWER_SHA: Record<number, string> = {"0":"3f989828898f9a20","1":"fdb49a35456e0bba","5":"bed7ff0ca5f4e42e","6":"0308f255edbe87ea","7":"43b65885aef2ff4f","8":"755cfaa768aabdff","9":"faa696de1f50b16c","12":"b8fac9178b56bacc","13":"064edcdcce8a9054","15":"e76f917d1059133b","17":"2b4bf5ab6f041355","18":"ed2b26998b05b5d5","20":"3c24d637187b992a","23":"c746535bc51b38f4","30":"48fef6e7caa1d760","31":"075cade9d5c7bf6d","37":"47292b084400bbb7","40":"98c18871ae417fd6","41":"972f95105751ca81","48":"4802b1550cf6e48f"}

test('the greeting and every forced answer match their approved full text exactly', () => {
  assert.equal(sha(GREETING), '3ec49ac347dc14f5')
  assert.deepEqual(Object.keys(FORCED_ANSWER_SHA), Object.keys(FORCED_ANSWERS))
  for (const [i, h] of Object.entries(FORCED_ANSWER_SHA)) assert.equal(sha(KNOWLEDGE[Number(i)].answer), h, 'entry ' + i)
})
